name: Contrast SAST Scan

on:
  workflow_dispatch:

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    name: Run Contrast SAST Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Contrast SAST Scan
        uses: ./
        with:
          contrast-api-url: ${{ vars.CONTRAST_API_URL }}
          jfrog-token: ${{ secrets.JFROG_TOKEN }}
          contrast-api-agent-version: ${{ vars.CONTRAST_AGENT_VERSION }}
          contrast-api-user-name: ${{ secrets.CONTRAST__API__USER_NAME }}
          contrast-api-api-key: ${{ secrets.CONTRAST__API__API_KEY }}
          contrast-api-service-key: ${{ secrets.CONTRAST__API__SERVICE_KEY }}
          contrast-api-organization: ${{ secrets.CONTRAST__API__ORGANIZATION }}
          contrast-api-auth-token: ${{ secrets.CONTRAST__AUTH__TOKEN }}
          contrast-api-resource-group: ${{ vars.CONTRAST_RESOURCE_GROUP }}

      # - name: Upload SAST Scan Results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: sast-scan-results
      #     path: path/to/scan-results #Update this path
